### ISSUE TITLE
Cannot find module step-definitions

### ISSUE THREAD

**Issue by dmitriy-ddr** [webdriverio/wdio-cucumber-framework#100]
Good afternoon, I ran into a popular problem when the cucumber does not see the step description files. I saw a lot of reports about this, but there was not described how to solve this problem.
wdio version is 4.12.0
wdio-cucumber-framework 1.1.0
cucumber-js version is 2.3.1
I add the cucumber module with wdio config

log:
C:\Users\node\Desktop\AT\1603>node_modules\.bin\wdio wdio.conf.js

ERROR: Cannot find module 'C:\Users\node\Desktop\AT\1603\features\step-definitions'
chrome
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at C:\Users\node\Desktop\AT\1603\node_modules\wdio-cucumber-framework\build\adapter.js:245:46
    at Array.forEach (<anonymous>)
    at CucumberAdapter.loadSpecFiles (C:\Users\node\Desktop\AT\1603\node_modules\wdio-cucumber-framework\build\adapter.js:237:34)
    at CucumberAdapter._callee$ (C:\Users\node\Desktop\AT\1603\node_modules\wdio-cucumber-framework\build\adapter.js:137:38)
    at tryCatch (C:\Users\node\Desktop\AT\1603\node_modules\wdio-cucumber-framework\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\node\Desktop\AT\1603\node_modules\wdio-cucumber-framework\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\node\Desktop\AT\1603\node_modules\wdio-cucumber-framework\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\node\Desktop\AT\1603\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\node\Desktop\AT\1603\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (C:\Users\node\Desktop\AT\1603\node_modules\core-js\library\modules\_export.js:35:28)
    at CucumberAdapter.<anonymous> (C:\Users\node\Desktop\AT\1603\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
    at CucumberAdapter.run (C:\Users\node\Desktop\AT\1603\node_modules\wdio-cucumber-framework\build\adapter.js:201:29)
    at Object._callee2$ (C:\Users\node\Desktop\AT\1603\node_modules\wdio-cucumber-framework\build\adapter.js:347:40)

**Comment by christian-bromann** [comment]
@dmitriy-ddr you need to define the file not the directory. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
