### ISSUE TITLE
Scenario Outline is not working

### ISSUE THREAD

**Issue by acuper** [webdriverio/wdio-cucumber-framework#111]
Versions: 
webdriverio@4.12.0
wdio-cucumber-framework@2.0.0 

Sample scenario:
```
Feature: Outline test

  Scenario Outline: Page - <page>
    Given I am on "<page>" page
    Then I should be on "<page>" page

    Examples:
      |  page     |
      |  Page1  |
      |  Page2  |
```

Error:
```
ERROR: Cannot read property 'steps' of undefined
chrome
Type    at CucumberEventListener.onTestStepStarted (C:\WORK\wdiotest\node_modules\wdio-cucumber-framework\build\cucumberEventListener.js:157:32)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at TestCaseRunner.emit (C:\WORK\wdiotest\node_modules\wdio-cucumber-framework\node_modules\cucumber\lib\runtime\test_case_runner.js:94:29)
    at TestCaseRunner.<anonymous> (C:\WORK\wdiotest\node_modules\wdio-cucumber-framework\node_modules\cucumber\lib\runtime\test_case_runner.js:191:14)
    at next (native)
    at tryCatcher (C:\WORK\wdiotest\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\WORK\wdiotest\node_modules\bluebird\js\release\generators.js:97:49)
    at TestCaseRunner.<anonymous> (C:\WORK\wdiotest\node_modules\bluebird\js\release\generators.js:201:15)
    at TestCaseRunner.aroundTestStep (C:\WORK\wdiotest\node_modules\wdio-cucumber-framework\node_modules\cucumber\lib\runtime\test_case_runner.js:210:22)
    at C:\WORK\wdiotest\node_modules\wdio-cucumber-framework\node_modules\cucumber\lib\runtime\test_case_runner.js:314:26
    at next (native)
    at tryCatcher (C:\WORK\wdiotest\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\WORK\wdiotest\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\WORK\wdiotest\node_modules\bluebird\js\release\generators.js:201:15
    at C:\WORK\wdiotest\node_modules\wdio-cucumber-framework\node_modules\cucumber\lib\runtime\test_case_runner.js:320:27
------------------------------------------------------------------
[chrome #0-0] Session ID: 1fd4763051c7de79cc08a55bb0cf1067
[chrome #0-0] Spec: C:\WORK\wdiotest\test\wdio\features\Test.feature
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0] Outline test
[chrome #0-0]
[chrome #0-0]     Page - Page1
[chrome #0-0]
[chrome #0-0]         Page - Page2
[chrome #0-0]
[chrome #0-0]
[chrome #0-0]
```

**Comment by krzywiecki** [comment]
Hi guys, any update on that? I also have the same issue when I try to run Scenario Outline. Everything works fine with normal Scenarios.

**Comment by christian-bromann** [comment]
> Hi guys, any update on that?

No, but feel free to propose a PR with a fix

**Comment by Lilly2016** [comment]
I'm getting the same error when I run Scenario Outline. 
`ERROR: Cannot read property 'steps' of undefined`

Is there a config or a syntax to use to avoid this issue?

**Comment by faceleg** [comment]
This does not seem fixed, I'm getting the same issue as @Lilly2016 with the following:

```@pre-register @ci
Feature: Submitting my details for pre-registration

  Scenario Outline: I want to see an error state when I submit the form without completing a field
    When  I type "<email>" in the home email field
    And   I type "<firstname>" in the home firstname field
    And   I type "<lastname>" in the home lastname field
    And   I click the home pre-register button
    Then I should see the <errorfields> highlighted

    Examples:
      | firstname | lastname | email                | errorfields       |
      | firstname | lastname | EMPTY                     | email              |
      | firstname |          | email@lightbox.co.nz | lastname           |
      |           | lastname | email@lightbox.co.nz | firstname          |
      |           |          | email@lightbox.co.n  | firstname,lastname |

```

**Comment by anilkoithara** [comment]
yes its not fixed I think, I am having the same issue .

ERROR: Cannot read property 'steps' of undefined
chrome

**Comment by walternolasco** [comment]
Hi,
Does anybody have a workaround to make it work meanwhile it is getting fixed?

Thanks!
