### ISSUE TITLE
Not able to start wdio.conf.js

### ISSUE THREAD

**Issue by RenanChagas** [webdriverio/wdio-cucumber-framework#118]
Here is the log from terminal
Obs.: Using version 2.0.1

```

ERROR: Unexpected token import
chrome
/Users/dkrechwa/Documents/Workspace/Offline/test-cucumber-react/test/behaviour/steps/testSteps.js:1
(function (exports, require, module, __filename, __dirname) { import chai from 'chai';
                                                              ^^^^^^

Syntax    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at loader (/Users/dkrechwa/Documents/Workspace/Offline/test-cucumber-react/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dkrechwa/Documents/Workspace/Offline/test-cucumber-react/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Module._load (module.js:497:3)
    at Function.hookedLoader [as _load] (/Users/dkrechwa/Documents/Workspace/Offline/test-cucumber-react/node_modules/mockery/mockery.js:111:12)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /Users/dkrechwa/Documents/Workspace/Offline/test-cucumber-react/node_modules/wdio-cucumber-framework/build/adapter.js:253:17
    at Array.forEach (<anonymous>)
    at CucumberAdapter.loadSpecFiles (/Users/dkrechwa/Documents/Workspace/Offline/test-cucumber-react/node_modules/wdio-cucumber-framework/build/adapter.js:244:34)
    at CucumberAdapter._callee$ (/Users/dkrechwa/Documents/Workspace/Offline/test-cucumber-react/node_modules/wdio-cucumber-framework/build/adapter.js:130:38)
    at tryCatch (/Users/dkrechwa/Documents/Workspace/Offline/test-cucumber-react/node_modules/regenerator-runtime/runtime.js:62:40)
```

**Comment by BorisOsipov** [comment]
@RenanChagas you need to use `babel` if you want use ES6 modules.

See example setup in https://github.com/webdriverio/cucumber-boilerplate
