### ISSUE TITLE
before hook is not executed in wdio.conf.js

### ISSUE THREAD

**Issue by ckurban** [webdriverio/wdio-cucumber-framework#160]
**Libraries - package.json:** 

```
"wdio-cucumber-framework": "^2.2.8",
"webdriverio": "4.13.0",
"cucumber": "^4.2.1",
```

**wdio.conf.js :** 

```
    before: function () {
        const envConfig = require('./testData');
        global.envConfig = envConfig;
    }
```

**Same setup works fine on below written stack :** 

```
"wdio-cucumber-framework": "0.1.0", 
"webdriverio": "4.13.0",
"cucumber": "^0.10.4",
```

 **Output:** 

```
**ERROR: envConfig is not defined**
chrome.68_0
Reference    at Object.<anonymous> (/Users/xxx/dev/xxx/test/api/xxxx/ws410.js:7:57)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Module._load (module.js:498:3)
    at Function.hookedLoader [as _load] (/Users/xxx/dev/xxx/node_modules/mockery/mockery.js:111:12)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/dev/xxx/test/step_definitions/delivery_steps.js:3:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Module._load (module.js:498:3)
    at Function.hookedLoader [as _load] (/Users/xxx/dev/xxx/node_modules/mockery/mockery.js:111:12)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /Users/xxx/dev/xxx/node_modules/wdio-cucumber-framework/build/adapter.js:259:17
    at Array.forEach (<anonymous>)
    at CucumberAdapter.loadSpecFiles (/Users/xxx/dev/xxx/node_modules/wdio-cucumber-framework/build/adapter.js:250:34)
    at CucumberAdapter._callee$ (/Users/xxx/dev/xxx/node_modules/wdio-cucumber-framework/build/adapter.js:135:38)
    at tryCatch (/Users/xxx/dev/xxx/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/xxx/dev/xxx/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/xxx/dev/xxx/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/xxx/dev/xxx/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/xxx/dev/xxx/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/Users/xxx/dev/xxx/node_modules/core-js/library/modules/_export.js:35:28)
    at CucumberAdapter.<anonymous> (/Users/xxx/dev/xxx/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at CucumberAdapter.run (/Users/xxx/dev/xxx/node_modules/wdio-cucumber-framework/build/adapter.js:214:29)
    at Object._callee2$ (/Users/xxx/dev/xxx/node_modules/wdio-cucumber-framework/build/adapter.js:347:40)
    at tryCatch (/Users/xxx/dev/xxx/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/xxx/dev/xxx/node_modules/regenerator-runtime/runtime.js:296:22)
hooks such as before does not work in latest wdio-cucumber-adapter as it is not setting values into global variable.
```

**Comment by christian-bromann** [comment]
@ckurban this should be fixed in the latest version of this package: https://www.npmjs.com/package/@wdio/cucumber-framework
