### ISSUE TITLE
session not created: Unable to create new service: ChromeDriverService

### ISSUE THREAD

**Issue by MaheshGooner** [webdriverio/wdio-cucumber-framework#171]
chromedriver fails to start

```

2019-05-21T13:30:39.563Z INFO @wdio/cli:Launcher: Run onPrepare hook
2019-05-21T13:30:42.845Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Selenium exited before it could start
Another Selenium process may already be running or your java version may be out of date.
Be sure to check the official Selenium release notes for minimum required java version: https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG

    at ChildProcess.errorIfNeverStarted (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/selenium-standalone/lib/start.js:158:10)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)

Continue...
2019-05-21T13:30:42.848Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js

RUNNING  0-0 in chrome - /src/features/LaunchGoogle.feature

Stdout:
[0-0] 2019-05-21T13:30:43.072Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2019-05-21T13:30:43.165Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-05-21T13:30:43.165Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
[0-0] 2019-05-21T13:30:43.183Z DEBUG webdriver: request failed due to status 33
[0-0] 2019-05-21T13:30:43.183Z INFO webdriver: Retrying 1/3
[0-0] 2019-05-21T13:30:43.183Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-05-21T13:30:43.184Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
[0-0] 2019-05-21T13:30:43.192Z DEBUG webdriver: request failed due to status 33
[0-0] 2019-05-21T13:30:43.192Z INFO webdriver: Retrying 2/3
[0-0] 2019-05-21T13:30:43.192Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-05-21T13:30:43.192Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
[0-0] 2019-05-21T13:30:43.199Z DEBUG webdriver: request failed due to status 33
[0-0] 2019-05-21T13:30:43.199Z INFO webdriver: Retrying 3/3
[0-0] 2019-05-21T13:30:43.200Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-05-21T13:30:43.200Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
[0-0] 2019-05-21T13:30:43.208Z DEBUG webdriver: request failed due to status 33

Stderr:
[0-0] 2019-05-21T13:30:43.183Z WARN webdriver: Request failed due to Unable to create new service: ChromeDriverService
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'mahesh-thuma', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-50-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
[0-0] 2019-05-21T13:30:43.192Z WARN webdriver: Request failed due to Unable to create new service: ChromeDriverService
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'mahesh-thuma', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-50-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
[0-0] 2019-05-21T13:30:43.199Z WARN webdriver: Request failed due to Unable to create new service: ChromeDriverService
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'mahesh-thuma', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-50-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
[0-0] 2019-05-21T13:30:43.208Z ERROR webdriver: Request failed due to session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'mahesh-thuma', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-50-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
     at getErrorFromResponseBody (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/webdriver/build/utils.js:349:10)
     at Request._callback (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/webdriver/build/request.js:121:64)
     at Request.self.callback (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:185:22)
     at Request.emit (events.js:182:13)
     at Request.EventEmitter.emit (domain.js:442:20)
     at Request.<anonymous> (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:1161:10)
     at Request.emit (events.js:182:13)
     at Request.EventEmitter.emit (domain.js:442:20)
     at IncomingMessage.<anonymous> (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:1083:12)
     at Object.onceWrapper (events.js:273:13)
[0-0] 2019-05-21T13:30:43.209Z ERROR @wdio/runner: session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'mahesh-thuma', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-50-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
     at getErrorFromResponseBody (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/webdriver/build/utils.js:349:10)
     at Request._callback (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/webdriver/build/request.js:121:64)
     at Request.self.callback (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:185:22)
     at Request.emit (events.js:182:13)
     at Request.EventEmitter.emit (domain.js:442:20)
     at Request.<anonymous> (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:1161:10)
     at Request.emit (events.js:182:13)
     at Request.EventEmitter.emit (domain.js:442:20)
     at IncomingMessage.<anonymous> (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:1083:12)
     at Object.onceWrapper (events.js:273:13)

Worker Error:
session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'mahesh-thuma', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-50-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
Stdout:
[0-0] 2019-05-21T13:30:43.072Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2019-05-21T13:30:43.165Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-05-21T13:30:43.165Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
[0-0] 2019-05-21T13:30:43.183Z DEBUG webdriver: request failed due to status 33
[0-0] 2019-05-21T13:30:43.183Z INFO webdriver: Retrying 1/3
[0-0] 2019-05-21T13:30:43.183Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-05-21T13:30:43.184Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
[0-0] 2019-05-21T13:30:43.192Z DEBUG webdriver: request failed due to status 33
[0-0] 2019-05-21T13:30:43.192Z INFO webdriver: Retrying 2/3
[0-0] 2019-05-21T13:30:43.192Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-05-21T13:30:43.192Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
[0-0] 2019-05-21T13:30:43.199Z DEBUG webdriver: request failed due to status 33
[0-0] 2019-05-21T13:30:43.199Z INFO webdriver: Retrying 3/3
[0-0] 2019-05-21T13:30:43.200Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-05-21T13:30:43.200Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
[0-0] 2019-05-21T13:30:43.208Z DEBUG webdriver: request failed due to status 33

Stderr:
[0-0] 2019-05-21T13:30:43.183Z WARN webdriver: Request failed due to Unable to create new service: ChromeDriverService
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'mahesh-thuma', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-50-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
[0-0] 2019-05-21T13:30:43.192Z WARN webdriver: Request failed due to Unable to create new service: ChromeDriverService
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'mahesh-thuma', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-50-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
[0-0] 2019-05-21T13:30:43.199Z WARN webdriver: Request failed due to Unable to create new service: ChromeDriverService
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'mahesh-thuma', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-50-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
[0-0] 2019-05-21T13:30:43.208Z ERROR webdriver: Request failed due to session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'mahesh-thuma', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-50-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
     at getErrorFromResponseBody (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/webdriver/build/utils.js:349:10)
     at Request._callback (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/webdriver/build/request.js:121:64)
     at Request.self.callback (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:185:22)
     at Request.emit (events.js:182:13)
     at Request.EventEmitter.emit (domain.js:442:20)
     at Request.<anonymous> (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:1161:10)
     at Request.emit (events.js:182:13)
     at Request.EventEmitter.emit (domain.js:442:20)
     at IncomingMessage.<anonymous> (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:1083:12)
     at Object.onceWrapper (events.js:273:13)
[0-0] 2019-05-21T13:30:43.209Z ERROR @wdio/runner: session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'mahesh-thuma', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-50-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
     at getErrorFromResponseBody (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/webdriver/build/utils.js:349:10)
     at Request._callback (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/webdriver/build/request.js:121:64)
     at Request.self.callback (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:185:22)
     at Request.emit (events.js:182:13)
     at Request.EventEmitter.emit (domain.js:442:20)
     at Request.<anonymous> (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:1161:10)
     at Request.emit (events.js:182:13)
     at Request.EventEmitter.emit (domain.js:442:20)
     at IncomingMessage.<anonymous> (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:1083:12)
     at Object.onceWrapper (events.js:273:13)
[0-0] 2019-05-21T13:30:43.209Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
     at Runner.run (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/@wdio/runner/build/index.js:91:74)
     at process._tickCallback (internal/process/next_tick.js:68:7)

Worker Error:
session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'mahesh-thuma', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-50-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
     at getErrorFromResponseBody (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/webdriver/build/utils.js:349:10)
     at Request._callback (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/webdriver/build/request.js:121:64)
     at Request.self.callback (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:185:22)
     at Request.emit (events.js:182:13)
     at Request.EventEmitter.emit (domain.js:442:20)
     at Request.<anonymous> (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:1161:10)
     at Request.emit (events.js:182:13)
     at Request.EventEmitter.emit (domain.js:442:20)
     at IncomingMessage.<anonymous> (/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/node_modules/request/request.js:1083:12)
     at Object.onceWrapper (events.js:273:13)

Test Suites:     0 passed, 1 failed, 1 total (100% completed)
Time:            🕕  3.71s

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ tests: `rm -rf allure-results && ./node_modules/.bin/wdio wdio.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ tests script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mahesh/.npm/_logs/2019-05-21T13_30_43_248Z-debug.log

```

**Comment by christian-bromann** [comment]
@MaheshGooner you are using v5 with Cucumber? This is not yet supported. Please follow https://github.com/webdriverio/webdriverio/pull/3667 for updates.

**Comment by MaheshGooner** [comment]
@christian-bromann i got this issue fixed and i am able to run cucumber with wdio 5

**Comment by abjerstedt** [comment]
@MaheshGooner please elaborate..... I haven't completed my PR yet, and so we don't support cucumber.

**Comment by MaheshGooner** [comment]
@abjerstedt I use the below configuration and i launch the selenium server separately but only once before the tests execute and i also install `chromedriver`

```
"devDependencies": {
    "@wdio/allure-reporter": "^5.7.11",
    "@wdio/local-runner": "^5.8.6",
    "@wdio/sync": "^5.8.6",
    "chromedriver": "^74.0.0",
    "wdio-chromedriver-service": "^5.0.1",
    "wdio-cucumber-framework": "2.2.8",
    "wdio-selenium-standalone-service": "~0.0.12"
  },
  "dependencies": {
    "@wdio/cli": "^5.8.6",
    "babel-preset-env": "^1.6.0",
    "babel-register": "^6.26.0",
    "selenium-standalone": "^6.8.0",
    "wdio-allure-reporter": "^0.6.0"
  }
```

I get one deprecation warning though 
```
[0-0] (node:20420) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocU
nsafe(), or Buffer.from() methods instead.
```
But i am able to run my cucumber tests without any issues.

**Comment by abjerstedt** [comment]
@MaheshGooner I don't see "webdriverio" in your dependencies at all... AFAIK, @wdio/cli isn't enough, and i have a feeling you are using v4 still.

Try nuking your node modules and yarn lock and starting fresh. wdio-cucumber-framework 2.2.8 will not work with v5.

**Comment by abjerstedt** [comment]
Actually... i'm 100% sure of it. Looking at your log, you are seeing logLevels that are v4. We don't use info/debug in v5.

**Comment by MaheshGooner** [comment]
I deleted my nodemodules and yarn.lock. reran the project and still all good.
I also have a CI runner on an ubuntu docker container no problems there as well.

**Comment by BorisOsipov** [comment]
@MaheshGooner you can remove all "@wdio/*" packages and everything still will be good :)

**Comment by MaheshGooner** [comment]
haha. sorry that doesn't work :D. you know i have a wdio.conf.js :)

**Comment by abjerstedt** [comment]
@MaheshGooner 
```
[0-0] 2019-05-21T13:30:43.072Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2019-05-21T13:30:43.165Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-05-21T13:30:43.165Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
[0-0] 2019-05-21T13:30:43.183Z DEBUG webdriver: request failed due to status 33
[0-0] 2019-05-21T13:30:43.183Z INFO webdriver: Retrying 1/3
[0-0] 2019-05-21T13:30:43.183Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-05-21T13:30:43.184Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
[0-0] 2019-05-21T13:30:43.192Z DEBUG webdriver: request failed due to status 33
[0-0] 2019-05-21T13:30:43.192Z INFO webdriver: Retrying 2/3
[0-0] 2019-05-21T13:30:43.192Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-05-21T13:30:43.192Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
[0-0] 2019-05-21T13:30:43.199Z DEBUG webdriver: request failed due to status 33
[0-0] 2019-05-21T13:30:43.199Z INFO webdriver: Retrying 3/3
[0-0] 2019-05-21T13:30:43.200Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-05-21T13:30:43.200Z INFO webdriver: DATA { capabilities:
    { alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
      firstMatch: [ {} ] },
   desiredCapabilities:
    { browserName: 'chrome',
      'goog:chromeOptions': { args: [Array] } } }
[0-0] 2019-05-21T13:30:43.208Z DEBUG webdriver: request failed due to status 33
```

You are definitively using Webdriverio v4. This is not a v5 log. That said, you are using v5 CLI, and you can see the v4 code printing to stdout.

How did you delete your node_modules, your lock and how did you run install?

**Comment by MaheshGooner** [comment]
i think you are right. when i created this ticket i might be using v4 but i migrated later to v5. i see there are issues with the logs but it doesn't stop me from running the tests.

```
2019-05-22T14:32:50.305Z WARN @wdio/cli: Can't identify message from worker: {"event":"test:pass","cid":"0-0","uid":"I launch OPAP7","title":"I launch OPAP","pending":false,"parent":"Webdriverio Google Launch5","type":"test","file":"src/features/LaunchGoogle.feature","err":{},"duration":4186,"runner":{"0-0":{"maxInstances":5,"browserName":"chrome"}},"specs":["/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/src/features/LaunchGoogle.feature"],"tags":[],"keyword":"When "}, ignoring!
2019-05-22T14:32:50.306Z WARN @wdio/cli: Can't identify message from worker: {"event":"test:start","cid":"0-0","uid":"I am on OPAP home page8","title":"I am on OPAP home page","pending":false,"parent":"Webdriverio Google Launch5","type":"test","file":"src/features/LaunchGoogle.feature","err":{},"duration":0,"runner":{"0-0":{"maxInstances":5,"browserName":"chrome"}},"specs":["/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/src/features/LaunchGoogle.feature"],"tags":[],"featureName":"Launch OPAP","scenarioName":"Webdriverio Google Launch","keyword":null}, ignoring!
[0-0] 2019-05-22T14:32:50.310Z INFO webdriver: COMMAND findElement("css selector", "span.c-header-desktop__button-text.is-active")
[0-0] 2019-05-22T14:32:50.311Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/1ad13efb1d8280496f99693467799bdc/element
[0-0] 2019-05-22T14:32:50.311Z INFO webdriver: DATA { using: 'css selector',
  value: 'span.c-header-desktop__button-text.is-active' }
[0-0] 2019-05-22T14:32:50.349Z INFO webdriver: RESULT { ELEMENT: '0.04306626526895507-1' }
[0-0] 2019-05-22T14:32:50.368Z INFO webdriver: COMMAND findElements("css selector", "span.c-header-desktop__button-text.is-active")
[0-0] 2019-05-22T14:32:50.368Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/1ad13efb1d8280496f99693467799bdc/elements
[0-0] 2019-05-22T14:32:50.368Z INFO webdriver: DATA { using: 'css selector',
  value: 'span.c-header-desktop__button-text.is-active' }
[0-0] 2019-05-22T14:32:50.385Z INFO webdriver: RESULT [ { ELEMENT: '0.04306626526895507-1' } ]
2019-05-22T14:32:50.391Z WARN @wdio/cli: Can't identify message from worker: {"event":"test:pass","cid":"0-0","uid":"I am on OPAP home page8","title":"I am on OPAP home page","pending":false,"parent":"Webdriverio Google Launch5","type":"test","file":"src/features/LaunchGoogle.feature","err":{},"duration":86,"runner":{"0-0":{"maxInstances":5,"browserName":"chrome"}},"specs":["/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/src/features/LaunchGoogle.feature"],"tags":[],"keyword":"Then "}, ignoring!
2019-05-22T14:32:50.392Z WARN @wdio/cli: Can't identify message from worker: {"event":"suite:end","cid":"0-0","uid":"Webdriverio Google Launch5","title":"Webdriverio Google Launch","pending":false,"parent":"Launch OPAP1","type":"suite","file":"src/features/LaunchGoogle.feature","err":{},"duration":4281,"runner":{"0-0":{"maxInstances":5,"browserName":"chrome"}},"specs":["/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/src/features/LaunchGoogle.feature"],"tags":[],"keyword":null}, ignoring!
2019-05-22T14:32:50.392Z WARN @wdio/cli: Can't identify message from worker: {"event":"suite:end","cid":"0-0","uid":"Launch OPAP1","title":"Launch OPAP","pending":false,"parent":null,"type":"suite","file":"src/features/LaunchGoogle.feature","err":{},"duration":4292,"runner":{"0-0":{"maxInstances":5,"browserName":"chrome"}},"specs":["/home/mahesh/Desktop/temp-projs/webdriverio-e2e-tests/src/features/LaunchGoogle.feature"],"tags":[],"keyword":null}, ignoring!
[0-0] 2019-05-22T14:32:50.495Z INFO webdriver: COMMAND deleteSession()
[0-0] 2019-05-22T14:32:50.496Z INFO webdriver: [DELETE] http://127.0.0.1:4444/wd/hub/session/1ad13efb1d8280496f99693467799bdc
[0-0] PASSED in chrome - /src/features/LaunchGoogle.feature
2019-05-22T14:32:50.663Z INFO @wdio/cli:Launcher: Run onComplete hook

Spec Files:      1 passed, 1 total (100% completed) in 00:00:06 
```

**Comment by abjerstedt** [comment]
@MaheshGooner Considering you are using your tests to verify production code, I STRONGLY suggest you rollback to v4 until i complete my PR. 

If you are that set on using v5 immediately, you can merge in the changes that i made in my PR to the cucumber-boilerplate, and then pulldown and crosslink my PR into your test repo. That said, my PR requires significant testing and you need to consider this as a pre-alpha release (aka expect bugs).

**Comment by MaheshGooner** [comment]
ok. i will try both the options. Thanks
