### ISSUE TITLE
Cannot use v2 from Github

### ISSUE THREAD

**Issue by istana** [webdriverio/wdio-cucumber-framework#68]
I wanted to use version 2 from Github branch (for Cucumber 2.x support), but it cannot be loaded. The package is downloaded correctly to *node_modules*. (node: v6.11.2)

in package.json

```
"wdio-cucumber-framework": "webdriverio/wdio-cucumber-framework#cucumberv2",
```

```
cat node_modules/wdio-cucumber-framework/package.json
{
  "name": "wdio-cucumber-framework",
  "version": "1.0.0-beta.0",
  "description": "A WebdriverIO plugin. Adapter for Cucumber2 testing framework.",
```

```
yarn run v0.27.5
$ ./node_modules/.bin/wdio wdio.conf.js
ERROR: Couldn't load "wdio-cucumber-framework" framework. You need to install it with `$ npm install wdio-cucumber-framework`!
Error: Cannot find module 'wdio-cucumber-framework'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Runner.initialiseFramework (/Users/monkeyking/vega/node_modules/webdriverio/build/lib/runner.js:517:24)
    at Runner._callee$ (/Users/monkeyking/vega/node_modules/webdriverio/build/lib/runner.js:100:55)
    at tryCatch (/Users/monkeyking/vega/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/monkeyking/vega/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/monkeyking/vega/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/monkeyking/vega/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)

    at Runner.initialiseFramework (/Users/monkeyking/vega/node_modules/webdriverio/build/lib/runner.js:523:23)
    at Runner._callee$ (/Users/monkeyking/vega/node_modules/webdriverio/build/lib/runner.js:100:55)
    at tryCatch (/Users/monkeyking/vega/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/monkeyking/vega/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/monkeyking/vega/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/monkeyking/vega/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/monkeyking/vega/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

Can you please point me to right direction?

**Comment by christian-bromann** [comment]
We still haven't merged the changes from https://github.com/webdriverio/wdio-cucumber-framework/pull/60 that would allow to use Cucumber v2. Please have a little bit more patience.

**Comment by istana** [comment]
oh, sorry, I didn't notice

**Comment by osmolyar** [comment]
Which version of cucumber are we supposed to be using now?

**Comment by istana** [comment]
@osmolyar try my configuration if it works:

```
    "cucumber": "^2.3.1",
    "wdio-cucumber-framework": "^1.0.2",
    "webdriverio": "^4.9.9"
```

I don't use *webdriverio-cucumber-js*.

**Comment by osmolyar** [comment]
Thank you very much for the input.  I tried it with the below in package.json, on a clean installation, installing everything locally or globally, and in either case I still get the error "ERROR: Couldn't load "wdio-cucumber-framework" framework. You need to install it with `$ npm install wdio-cucumber-framework`!"


 "dependencies": {
    "Faker": "^0.7.2",
    "colors": "^1.1.2",
    "download-file": "^0.1.5",
    "follow-redirects": "^1.2.1",
    "lodash": "^4.17.4",
	"cucumber": "2.3.1",
    "wdio-cucumber-framework": "^1.0.2",
    "wdio-junit-reporter": "^0.2.0",
    "wdio-spec-reporter": "0.0.5",
    "webdriverio": "^4.9.9",
    "yargs": "^6.6.0"
  },
  "devDependencies": {
    "wdio-cucumber-framework": "^1.0.2"
  }

**Comment by istana** [comment]
That's unusual behavior. Here are some steps that might help. Some are basic, but just to be sure.

- `yarn install` or `npm install` after package.json was changed
- run webdriver binary from node_modules `./node_modules/.bin/wdio wdio.conf.js`
- remove *node_modules* directory and run `yarn install` again
- last resort - remove *node_modules* directory and lock file - `yarn.lock` and run `yarn install`

There may be also a clash between global and local scope and a global package is preferred. I'd remove all global packages and use only those from *node_modules*. It helped me.

**Comment by osmolyar** [comment]
@istana, thanks, it finally worked after uninstalling everything locally and globally and deleting node_modules, and installing the relevant modules globally.  (Though it still doesn't seem to be recognizing my step_definitions folder from Cucumber require opts.)
