### ISSUE TITLE
Support for cucumber 3.1.0 with i18n

### ISSUE THREAD

**Issue by glaudiston** [webdriverio/wdio-cucumber-framework#82]
I want to use cucumber feature files in my language (pt). Cucumber cli since 3.1.0 has support for i18n with the command line argument `--language=pt`. 
I tried to change the cucumber version in `package.json` but it seems incompatible.

Can you provide any light on this?

> ERROR: Cannot set property 'World' of undefined
firefox
Type    at setWorldConstructor (~/sources/comissaoGerentes/node_modules/wdio-cucumber-framework/node_modules/cucumber/lib/support_code_library_builder/index.js:53:29)
    at Object.<anonymous> (~/sources/comissaoGerentes/features/step-definitions.js:18:1)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Module._load (module.js:486:3)
    at Function.hookedLoader [as _load] (~/sources/comissaoGerentes/node_modules/wdio-cucumber-framework/node_modules/mockery/mockery.js:111:12)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at ~/sources/comissaoGerentes/node_modules/wdio-cucumber-framework/build/adapter.js:231:17
    at Array.forEach (<anonymous>)
    at CucumberAdapter.loadSpecFiles (~/sources/comissaoGerentes/node_modules/wdio-cucumber-framework/build/adapter.js:222:39)
    at CucumberAdapter._callee$ (~/sources/comissaoGerentes/node_modules/wdio-cucumber-framework/build/adapter.js:129:38)
    at tryCatch (~/sources/comissaoGerentes/node_modules/wdio-cucumber-framework/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (~/comissaoGerentes/node_modules/wdio-cucumber-framework/node_modules/regenerator-runtime/runtime.js:303:22)

**Comment by christian-bromann** [comment]
Fixed by #104
